// courses.js

export const courses = [
    {
      id: '1',
      name: 'Operating Systems',
      code: 'CS101',
      teacher: 'Dr. John Doe',
      classMode: 'Online',
      timing: 'Mon, Wed, Fri - 10:00 AM - 11:30 AM',
      status: 'upcoming',
    },
    {
      id: '2',
      name: 'Database Systems',
      code: 'CS102',
      teacher: 'Prof. Jane Smith',
      classMode: 'In-Person',
      timing: 'Tue, Thu - 9:00 AM - 10:30 AM',
      status: 'upcoming',
    },
    {
      id: '3',
      name: 'Computer Networks',
      code: 'CS103',
      teacher: 'Dr. Emily Johnson',
      classMode: 'Hybrid',
      timing: 'Mon, Wed - 11:30 AM - 1:00 PM',
      status: 'upcoming',
    },
    {
      id: '4',
      name: 'Artificial Intelligence',
      code: 'CS104',
      teacher: 'Dr. Robert Brown',
      classMode: 'Online',
      timing: 'Mon, Wed - 2:00 PM - 3:30 PM',
      status: 'upcoming',
    },
    {
      id: '5',
      name: 'Machine Learning',
      code: 'CS105',
      teacher: 'Prof. Sarah White',
      classMode: 'In-Person',
      timing: 'Tue, Thu - 11:30 AM - 1:00 PM',
      status: 'upcoming',
    },
    {
        id: '11',
        name: 'UI Design',
        code: 'CSP201',
        teacher: 'Dr. John Doe',
        classMode: 'Online',
        timing: 'Mon, Wed, Fri - 10:00 AM - 11:30 AM',
        status: 'ongoing',  // Ongoing class
      },
    {
      id: '6',
      name: 'Software Engineering',
      code: 'CS106',
      teacher: 'Dr. Jason Green',
      classMode: 'Hybrid',
      timing: 'Fri - 1:00 PM - 3:00 PM',
      status: 'past',
    },
    {
      id: '7',
      name: 'Data Structures',
      code: 'CS107',
      teacher: 'Prof. Emma Brown',
      classMode: 'Online',
      timing: 'Mon, Wed, Fri - 8:30 AM - 10:00 AM',
      status: 'past',
    },
    {
      id: '8',
      name: 'Database Management',
      code: 'CS108',
      teacher: 'Dr. Michael Lee',
      classMode: 'In-Person',
      timing: 'Tue, Thu - 3:00 PM - 4:30 PM',
      status: 'past',
    },
    {
      id: '9',
      name: 'Digital Circuits',
      code: 'CS109',
      teacher: 'Prof. Emily White',
      classMode: 'Hybrid',
      timing: 'Mon, Wed - 2:00 PM - 4:00 PM',
      status: 'past',
    },
    {
      id: '10',
      name: 'Computer Graphics',
      code: 'CS110',
      teacher: 'Dr. Samuel Green',
      classMode: 'Online',
      timing: 'Fri - 10:00 AM - 12:00 PM',
      status: 'past',
    },
  ];
  